# Generated by Django 4.2.5 on 2023-09-11 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('amount', models.IntegerField(default=0)),
                ('description', models.TextField(default='')),
                ('artist', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('debut_date', models.DateField(blank=True, null=True)),
                ('members', models.TextField(default='')),
                ('former_members', models.TextField(default='')),
                ('sub_units', models.TextField(default='')),
                ('price', models.IntegerField(default=0)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
