# Generated by Django 4.2.5 on 2023-09-20 03:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('debut_date', models.DateField(blank=True, null=True)),
                ('disband_date', models.DateField(blank=True, null=True)),
                ('members', models.CharField(default='', max_length=1000)),
                ('former_members', models.CharField(default='', max_length=1000)),
                ('sub_units', models.TextField(default='')),
                ('supporters', models.CharField(default='', max_length=1000)),
                ('description', models.TextField(default='')),
                ('artist_pic', models.ImageField(blank=True, null=True, upload_to='artist_pics/')),
                ('artist_logo', models.ImageField(blank=True, null=True, upload_to='artist_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('price', models.IntegerField(default=0)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('tracklist', models.CharField(default='', max_length=2000)),
                ('album_cover', models.ImageField(blank=True, null=True, upload_to='album_covers/')),
                ('amount', models.IntegerField(default=0)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.artist')),
            ],
        ),
    ]
