# Generated by Django 4.2.5 on 2023-09-11 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_item_disband_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tracklist',
            field=models.TextField(default=''),
        ),
    ]
