# Generated by Django 4.2.5 on 2023-09-11 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_item_tracklist'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='supporters',
            field=models.CharField(default='', max_length=255),
        ),
    ]
