# Generated by Django 4.2.5 on 2023-09-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_item_supporters'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='album_cover',
            field=models.ImageField(blank=True, null=True, upload_to='album_covers/'),
        ),
        migrations.AddField(
            model_name='item',
            name='artist_pic',
            field=models.ImageField(blank=True, null=True, upload_to='artist_images/'),
        ),
    ]
