# Generated by Django 4.2.5 on 2023-09-12 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_item_album_cover_item_artist_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='album_cover',
            field=models.ImageField(blank=True, null=True, upload_to='albums/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='artist_pic',
            field=models.ImageField(blank=True, null=True, upload_to='artists/'),
        ),
    ]
