# Generated by Django 4.2.5 on 2023-09-12 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_item_album_cover_alter_item_artist_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='artist_logo',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='album_cover',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='artist_pic',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
